etherpad_port: 9001
etherpad_admin_password: O4%Q2m2DaGuuf
etherpad_default_pad_text: |
  ğŸ‘‹ Welcome to MeshPad!\n\n

  This is a shared public document for the mesh network.\n\n

  - Type to co-create with others nearby\n
  - Create new pads by changing the URL (e.g. /my-note)\n
  - Find existing pads by looking at 'All Pads' on the homepage\n\n

  ğŸŒ We're offline, but together.

postgres_container_name: postgres
postgres_db: etherpad
postgres_user: admin
postgres_password: admin
